language: generic
sudo: reqired

services:
    - docker

before_install:
    - docker build -t vdrozdovskyi/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vdrozdovskyi/react-test npm test -- --coverage

after_success:
    - docker build -t vdrozdovskyi/multi-client ./client
    - docker build -t vdrozdovskyi/multi-nginx ./nginx 
    - docker build -t vdrozdovskyi/multi-server ./server
    - docker build -t vdrozdovskyi/multi-worker ./worker 
    
    # Login docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Push images to docker
    - docker push vdrozdovskyi/multi-client
    - docker push vdrozdovskyi/multi-nginx 
    - docker push vdrozdovskyi/multi-server
    - docker push vdrozdovskyi/multi-worker

deploy:
    # edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-926417195330"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY